version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - backend

  kibana:
    container_name: kibana
    image: kibana:7.8.1
    environment:
      - i18n.locale=zh-CN
      - xpack.graph.enabled=true
    ports:
      - "5601:5601"
    networks:
      - backend

  cerebro:
    container_name: cerebro
    image: lmenezes/cerebro:0.9.2
    ports:
      - "9100:9000"
    command:
      - -Dhosts.0.host=http://elasticsearch:9200
    networks:
      - backend
